#障碍物最大范围
obstacle_range: 5.5
#自由空间最大范围
raytrace_range: 8
#机器人占用面积
footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]


map_type: costmap
observation_sources: scan

scan: {sensor_frame: velodyne, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

pointcloud: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}
#障碍物layer
obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.7
  origin_z:             0.0
  z_resolution:         0.1
  z_voxels:             10
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 3.0
  raytrace_range: 3.5
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  publish_voxel_map: false
  observation_sources:  scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.70
    inf_is_valid: true
  bump:
    data_type: PointCloud2
    topic: rslidar_points
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 0.7
#障碍物膨胀系数
inflation_layer1:
 enabled:              true
 cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.7  # max. distance from an obstacle at which costs are incurred for planning paths.

inflation_layer2:
 enabled:              true
 cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.30  # max. distance from an obstacle at which costs are incurred for planning paths.
