global_costmap:
  #global_frame odom
  global_frame: odom
  robot_base_frame: base_link
  #地图更新频率
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.5
  #静态地图设置
  static_map: true
  plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  # - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer1,         type: "costmap_2d::InflationLayer"}
