local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  #地图更新频率
  update_frequency: 6.0
  publish_frequency: 6.0
  transform_tolerance: 0.5 
  #静态地图设置
  static_map: true  
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  plugins:
  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer2,         type: "costmap_2d::InflationLayer"}
