shutdown_costmaps: false
#控制频率
controller_frequency: 20.0 #10
planner_patience: 5.0 #5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
#规划频率
planner_frequency: 1.0 #1 
oscillation_timeout: 10.0
oscillation_distance: 0.2
